plugins {
	id 'net.fabricmc.fabric-loom'
	id 'maven-publish'
}

configurations {
	commonJava {
		canBeResolved = true
	}
	commonResources {
		canBeResolved = true
	}
}

repositories {
	maven { url = 'https://maven.terraformersmc.com/releases/'
		content { includeGroupAndSubgroups("com.terraformersmc") }
	}
	maven { url = 'https://maven.fallenbreath.me/releases'
		content { includeGroupAndSubgroups("me.fallenbreath") }
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
	implementation "com.google.code.findbugs:jsr305:3.0.2"
	include(implementation("me.fallenbreath:conditional-mixin-fabric:${project.conditionalmixin_version}"))
	compileOnly "com.terraformersmc:modmenu:${project.mod_menu_version}"

	implementation files("${rootProject.projectDir}/libs/${project.malilib_fabric_file}")

	commonJava project(path: ':common', configuration: 'commonJava')
	commonResources project(path: ':common', configuration: 'commonResources')
}

// Compile common sources directly
tasks.named('compileJava', JavaCompile) {
	dependsOn(configurations.commonJava)
	source(configurations.commonJava)
}

base {
	group = project.group + "." + project.mod_id
	archivesName = "tweakeroo-fabric-${project.minecraft_version_out}"
	version = project.mod_version
	if (version.endsWith('-dev')) {
		version += "." + new Date().format('yyyyMMdd.HHmmss')
	}
}

loom {
	accessWidenerPath = file("src/main/resources/tweakeroo.accesswidener")
}

processResources {
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
	from(configurations.commonResources) {
		exclude '**/tweakeroo.accesswidener'
		exclude '**/mixins.tweakeroo.json'
		exclude '**/*.xcf'
		exclude '**/xcf'
	}
	inputs.property "mod_version", project.mod_version
	filesMatching("fabric.mod.json") {
		expand "mod_version": project.mod_version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	it.options.release = 25
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
	withSourcesJar()
}

jar {
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
	from(rootProject.file("LICENSE.txt")) {
		rename { "${it}_${base.archivesName}"}
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			artifactId = base.archivesName.get()
			from components.java
		}
	}
	repositories {
		maven {
			url = "${rootProject.projectDir}/CommonMaven"
		}
	}
}
