plugins {
	id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT' apply false
	id 'net.neoforged.moddev' version '2.0.144' apply false
}

allprojects {
	group = "fi.dy.masa"
	version = findProperty("mod_version") ?: "0.29.3"
}

subprojects {
	apply plugin: 'java'
	apply plugin: 'maven-publish'

	tasks.withType(JavaCompile).configureEach {
		it.options.encoding = "UTF-8"
		it.options.release = 25
	}

	java {
		sourceCompatibility = JavaVersion.VERSION_25
		targetCompatibility = JavaVersion.VERSION_25
		withSourcesJar()
	}
}
